### ISSUE TITLE
Any chance that you would bring Metal support to llama.cpp?

### ISSUE THREAD

**Issue by kchro3** [guinmoon/llmfarm_core.swift#1]
Hey, I saw your repo, and I think that you're working on really cool stuff!

I was trying to hack out figuring out how to enable Metal on llama.cpp for Swift apps, and it looks like you were able to hack something together. Do you have any plans to bring your changes to llama.cpp, and if not, would you please share any insights into how you overcame them? I'm new to Swift, so I can't really make heads or tails of it but was able to run your repo w/ Metals successfully.

**Comment by guinmoon** [comment]
> Hey, I saw your repo, and I think that you're working on really cool stuff!
> 
> I was trying to hack out figuring out how to enable Metal on llama.cpp for Swift apps, and it looks like you were able to hack something together. Do you have any plans to bring your changes to llama.cpp, and if not, would you please share any insights into how you overcame them? I'm new to Swift, so I can't really make heads or tails of it but was able to run your repo w/ Metals successfully.

Hello. I'm sorry for the late reply. I had ideas to make changes to `ggml-metal.m`, but I noticed you already did it. Is there anything else I can do to help?

**Comment by kchro3** [comment]
No, but thanks anyways! Your repo was a helpful reference.
