### ISSUE TITLE
Removing unsafe flags when debugging

### ISSUE THREAD

**Issue by chakkaradeep** [guinmoon/llmfarm_core.swift#11]
Hi there,

ReadMe mentions removing unsafe flags, but I am unable to do so if I add it as a Package Dependency.

Are you suggesting I have to manually build the source without the unsafe flags to use in my project?

Apologies if this sounds too simple of a question, I am figuring out how to build a Mac OS chat desktop application that interacts with a mistral GGUF model. 

Thanks,
Chaks

**Comment by guinmoon** [comment]
Yes you have to manually build the source without the flags.

**Comment by draftin1** [comment]
I am having this same issue. What does it require to manually build the source?
