### ISSUE TITLE
The package product cannot be used as a dependency of this target because it uses unsafe build flags

### ISSUE THREAD

**Issue by 1234igor** [guinmoon/llmfarm_core.swift#12]
I am getting this error in Xcode when trying to build the newly created project with this package imported:

> The package product 'llmfarm_core' cannot be used as a dependency of this target because it uses unsafe build flags.

It doesn't work even when I'm importing the package locally and commenting out all the `.unsafeFlags` lines in the `Package.swift`

I also tried the approach suggested [here](https://stackoverflow.com/a/67895931) with importing a specific commit, but it didn't help

How do you add this package to the Xcode project? 

Sorry, I'm not proficient with packages 🙂

**Comment by guoyingtao** [comment]
I have the same issue.

**Comment by guoyingtao** [comment]
I solved this issue by using Commit for SPF
<img width="896" alt="image" src="https://github.com/guinmoon/llmfarm_core.swift/assets/26723384/d785f1c6-c030-49e8-90b9-1de275af63cf">

but I saw a compile issue as below

<img width="420" alt="image" src="https://github.com/guinmoon/llmfarm_core.swift/assets/26723384/977cf7c2-8849-4724-869c-1becacf91cf4">

**Comment by guinmoon** [comment]
Hi. This is problem with [Xcode 15](https://github.com/guinmoon/LLMFarm/issues/19).

**Comment by guoyingtao** [comment]
@guinmoon 
Thank you! New Xcode solved the issue.

**Comment by buhe** [comment]
Although using Commit for SPF , the library is considered an unstable-version package after relying on commit

**Comment by small-cactus** [comment]
Xcode 15.3, still have the issue.

**Comment by rakeshtwinciti** [comment]
Xcode 15.4, still have the issue.
