### ISSUE TITLE
Cannot find type 'ModelContextParams' in scope

### ISSUE THREAD

**Issue by 1234igor** [guinmoon/llmfarm_core.swift#13]
Hey! Trying to import the package but still face some issues

What I do:

1. Create a new SwiftUI app
2. File → Add Package Dependencies...
3. Add `llmfarm_core.swift` package, specify the latest commit hash
4. Inside ContentView.swift:
- `import llmfarm_core`
- Add code: 
```
.onAppear() {
            let maxOutputLength = 256
            var total_output = 0

            var input_text = "State the meaning of life."

            let ai = AI(_modelPath: "llama-2-7b-chat.Q4_K_M.gguf",_chatName: "chat")
            var params:ModelContextParams = .default
            params.use_metal = true

            try? ai.loadModel(ModelInference.LLama_gguf,contextParams: params)
            ai.model.promptFormat = .LLaMa

          
        }
```
7. The errors I get:
- `Cannot find type 'ModelContextParams' in scope`
- `Value of type 'LLMBase' has no member 'promptFormat'`

How do I resolve this?

**Comment by buhe** [comment]
see https://github.com/guinmoon/llmfarm_core.swift/pull/7

**Comment by 1234igor** [comment]
Thank you @buhe, I am not getting error here anymore: 

```
var params:ModelAndContextParams = .default
```



However, this line: 

```
ai.model.promptFormat = .LLaMa
```




still throws these errors:

```
Cannot infer contextual base in reference to member 'LLaMa'
Value of type 'LLMBase' has no member 'promptFormat'
```

**Comment by buhe** [comment]
Can refer to https://github.com/guinmoon/llmfarm_core.swift/blob/main/Examples/llama_metal.swift

**Comment by guinmoon** [comment]
Thanks for the tips @buhe! I will update the readme and examples later.
