### ISSUE TITLE
Xcode15.0 build error: The package product 'llmfarm_core' cannot be used as a dependency of this target because it uses unsafe build flags.

### ISSUE THREAD

**Issue by HoodL** [guinmoon/llmfarm_core.swift#18]
I used SPM to add llmfarm_core into my project and have already commented ".unsafeFlags(["-Ofast"])", but still reported an error：
![image](https://github.com/guinmoon/llmfarm_core.swift/assets/8132433/7e844390-d601-4acd-a25a-8463f415deeb)

**Comment by buhe** [comment]
#12
