### ISSUE TITLE
lora adapter support

### ISSUE THREAD

**Issue by gwtvanderheijden** [guinmoon/llmfarm_core.swift#2]
Not a real issue, but more a question. 
current llama.cpp code supports loading also in lora adapters. Is this also supported by llmfarm_core.swift as I do not see that back in the LLMFarm code/application. 
In case it is supported, is there an example on how to use it?

**Comment by guinmoon** [comment]
Doesn't support it at the moment, but I'm working on it. Unfortunately, calling the `llama_model_apply_lora_from_file` function in llmfarm_core currently causes the application to crash.

**Comment by gwtvanderheijden** [comment]
ok, thanks. I am currently using llama_model_apply_lora_from_file  in the latest llama.cpp release which works with macOS. I do not know which llama.cpp/ggml release is in the current code and it maybe only a pull-in of the latest release. But of coarse  I do not know the details of the code.

**Comment by guinmoon** [comment]
> ok, thanks. I am currently using llama_model_apply_lora_from_file  in the latest llama.cpp release which works with macOS. I do not know which llama.cpp/ggml release is in the current code and it maybe only a pull-in of the latest release. But of coarse  I do not know the details of the code.

could you share the model and lora file with which it works correctly for you? thanks

**Comment by guinmoon** [comment]
[added](https://github.com/guinmoon/llmfarm_core.swift/commit/f2938fbc7054885f9c25c1d61cb5ccab4be645dc)
