### ISSUE TITLE
 `unsafe build flags` error when including llmfarm_core

### ISSUE THREAD

**Issue by minoskt** [guinmoon/llmfarm_core.swift#5]
Hello

Each time I add `llmfarm_core` package as a dependency I see the following error:
`The package product 'llmfarm_core' cannot be used as a dependency of this target because it uses unsafe build flags.`

Any idea why?

**Comment by guinmoon** [comment]
https://stackoverflow.com/questions/67889931/the-package-product-mylibrary-cannot-be-used-as-a-dependency-of-this-target-be
Try the solution suggested here. Or add a library by dragging and dropping a directory into the project.  I will update the Readme later.

**Comment by minoskt** [comment]
Solution didn't work for me, but drag and dropping the framework did. Thank you.
